apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: kube-prometheus-stack
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "40.3.1"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
  interval: 50m
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    prometheus:
      prometheusSpec:
      retention: 7d
