apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: kube-prometheus-stack
spec:
  chart:
    spec:
      version: "43.2.1"
  values:
    prometheus:
      prometheusSpec:
        retention: 7d
