apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: kube-prometheus-stack
spec:
  chart:
    spec:
      version: "2.8.3"
  values:
    loki:
      enabled: true
      isDefault: false
