apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: loki-stack
spec:
  releaseName: loki-stack
  chart:
    spec:
      chart: loki-stack
      version: "2.8.3"
      sourceRef:
        kind: HelmRepository
        name: loki-stack
  interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    loki:
      enabled: true
      isDefault: false
