apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app2
  namespace: app2
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: app2
  path: ./app2/overlays/prod
  prune: true
