apiVersion: v1
kind: Namespace
metadata:
  name: app1
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: app1
  namespace: app1
spec:
  interval: 5m0s
  url: https://github.com/cod-r/app1-k8s
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app1
  namespace: app1
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: app1
  path: ./app1/overlays/prod
  prune: true
